{
 "title": "counting events",
 "description": "counting events",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Sessions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(DISTINCT sessionId) AS \"Unique Sessions\"\nFROM default.epas_default\nWHERE\n  timestamp >= toDateTime($__from / 1000)\n  AND timestamp <= toDateTime($__to / 1000)"
    }
   ]
  },
  {
   "title": "Device Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  deviceType   AS category,\n  COUNT(*)     AS value\nFROM default.epas_default\nWHERE\n  timestamp >= toDateTime($__from / 1000)\n  AND timestamp <= toDateTime($__to   / 1000)\n  AND event = 'metadata'\n  AND deviceType IS NOT NULL\nGROUP BY\n  deviceType"
    }
   ]
  },
  {
   "title": "Initiated Sessions (5mins)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfInterval(toDateTime(timestamp), INTERVAL 5 MINUTE) AS time,\n  'initiated_sessions' AS metric,\n  COUNT(DISTINCT sessionId) AS value\nFROM default.epas_default\nWHERE\n  timestamp >= toDateTime($__from / 1000)\n  AND timestamp <= toDateTime($__to / 1000)\n  AND event = 'init'\nGROUP BY\n  time,\n  metric\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Event Type",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "\nSELECT\n  toStartOfMinute(timestamp) AS \"time\",\n  event                      AS \"metric\",\n  count(*)                   AS \"value\"\nFROM default.epas_default\nWHERE\n  timestamp >= toDateTime($__from / 1000)\n  AND timestamp <= toDateTime($__to   / 1000)\nGROUP BY\n  time, metric\nORDER BY\n  time ASC, metric\n\n"
    }
   ]
  }
 ]
}